import {StyleSheet} from 'react-native';

export const Font = StyleSheet.create({
  Main_Title_34_EB: {
    fontFamily: 'System',
    fontSize: 34,
    fontStyle: 'normal',
    fontWeight: '800',
    lineHeight: 42,
    color: 'black',
  },
  Title01_28_M: {
    fontFamily: 'System',
    fontSize: 24,
    fontStyle: 'normal',
    fontWeight: '500',
    lineHeight: 32,
    letterSpacing: 0.01,
    color: 'black',
  },
  Title02_22_R: {
    fontFamily: 'System',
    fontSize: 22,
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: 32,
    letterSpacing: 0.01,
    color: 'black',
  },
  Title02_22_B: {
    fontFamily: 'System',
    fontSize: 22,
    fontStyle: 'normal',
    fontWeight: '700',
    lineHeight: 32,
    letterSpacing: 0.01,
    color: 'black',
  },
  Title03_20_R: {
    fontFamily: 'System',
    fontSize: 20,
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: 30,
    letterSpacing: 0.01,
    color: 'black',
  },
  Headline_16_SM: {
    fontFamily: 'System',
    fontSize: 16,
    fontStyle: 'normal',
    fontWeight: '600',
    lineHeight: 24,
    letterSpacing: 0.01,
    color: 'black',
  },
  Body_16_R: {
    fontFamily: 'System',
    fontSize: 16,
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: 22,
    letterSpacing: 0.01,
    color: 'black',
  },
  Body_14_R: {
    fontFamily: 'System',
    fontSize: 14,
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: 19,
    letterSpacing: 0.01,
    color: 'black',
  },
  Fontnote_14_R: {
    fontFamily: 'System',
    fontSize: 14,
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: 22,
    letterSpacing: 0.01,
    color: 'rgba(0,0,0,0.33)',
  },
  Footnote_14_R: {
    fontFamily: 'System',
    fontSize: 14,
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: 22,
    letterSpacing: 0.01,
    color: '#ffffff',
  },
  Footnote_14_SB: {
    fontFamily: 'System',
    fontSize: 14,
    fontStyle: 'normal',
    fontWeight: '600',
    lineHeight: 22,
    letterSpacing: 0.01,
    color: '#ffffff',
  },
  Caption01_12_R: {
    fontFamily: 'System',
    fontSize: 12,
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: 14,
    letterSpacing: 0.01,
    color: 'rgba(0,0,0,0.5)',
  },
  Caption01_14_R: {
    fontFamily: 'System',
    fontSize: 14,
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: 18,
    letterSpacing: 0.01,
    color: 'rgba(0,0,0,0.5)',
  },
  Caption01_14_B: {
    fontFamily: 'System',
    fontSize: 14,
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: 16,
    letterSpacing: 0.01,
    color: 'black',
  },
  Caption02_10_R: {
    fontFamily: 'System',
    fontSize: 10,
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: 12,
    letterSpacing: 0.01,
    color: 'black',
  },
  Headline_20_SM: {
    fontFamily: 'System',
    fontSize: 20,
    fontStyle: 'normal',
    fontWeight: '600',
    lineHeight: 24,
    letterSpacing: 0.01,
    color: 'black',
  },
});
